CREATE TABLE mensajes (
	id_mensaje INT NOT NULL AUTO_INCREMENT,
    autor VARCHAR(30) NOT NULL DEFAULT "PERRO LOCO",
    cuerpo VARCHAR(255) NOT NULL,
    fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id_mensaje)
);